language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
script:   
  [pytest]
  testpaths =
      tests
      skift
  norecursedirs=dist build .tox scripts
  addopts =
      --doctest-modules
      --cov=skift
      -r a
      -v
after_success:
  - codecov # submit coverage
